<?php
namespace Sil\DevPortal\components;

/**
 * Since we now namespace our models, the relationships (defined in the
 * `relations()` function) must use the full classpath for any classes.
 * However, since the ___Base classes are auto-generated by Yii (via Gii),
 * any such changes we make to those classes risk being overwritten and lost.
 * This trait solves that by providing a way to add the correct path to the
 * class names.
 * 
 * NOTE: Any relations not fixed by this trait should use the correct full
 *       classpath.
 * 
 * NOTE 2: In case a subclass doesn't override the relations() method, we do so
 *         here, simply fixing and returning the parent class's relations()
 *         data. If the subclass does override the relations() method, this copy
 *         of the relations() method will not be called.
 *
 * @author Matt Henderson
 */
trait FixRelationsClassPathsTrait
{
	public function fixRelationsClassPaths($relations)
    {
        $fixedRelations = array();
        
        foreach ($relations as $name => $options) {
            $fixedRelations[$name] = $options;
            $fixedRelations[$name][1] = '\\Sil\\DevPortal\\models\\' . $options[1];
        }
        
        return $fixedRelations;
    }
    
    public function relations()
    {
        return $this->fixRelationsClassPaths(parent::relations());
    }
}
